openapi: 3.0.0
servers:
  - url: https://catfact.ninja
info:
  title: Cat Fact API
  description: An API for facts about cats
  contact:
    email: contact@catfact.ninja
  version: 1.0.0
paths:
  /breeds:
    get:
      tags:
        - Breeds
      summary: Get a list of breeds
      description: Returns a a list of breeds
      operationId: getBreeds
      parameters:
        - name: page
          in: query
          description: page number
          required: false
          schema:
            type: integer
            format: int64
        - name: limit
          in: query
          description: limit the amount of results returned
          required: false
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                allOf:
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: '#/components/schemas/Breed'
                  - $ref: '#/components/schemas/PageResult'
  /fact:
    get:
      tags:
        - Facts
      summary: Get Random Fact
      description: Returns a random fact
      operationId: getRandomFact
      parameters:
        - name: max_length
          in: query
          description: maximum length of returned fact
          required: false
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CatFact'
        '404':
          description: Fact not found
  /facts:
    get:
      tags:
        - Facts
      summary: Get a list of facts
      description: Returns a a list of facts
      operationId: getFacts
      parameters:
        - name: max_length
          in: query
          description: maximum length of returned fact
          required: false
          schema:
            type: integer
            format: int64
        - name: page
          in: query
          description: page number
          required: false
          schema:
            type: integer
            format: int64
        - name: limit
          in: query
          description: limit the amount of results returned
          required: false
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  allOf:
                    - type: object
                      properties:
                        data:
                          type: array
                          items:
                            $ref: '#/components/schemas/CatFact'
                    - $ref: '#/components/schemas/PageResult'
components:
  schemas:
    Breed:
      title: Breed model
      description: Breed
      required:
        - breed
        - country
        - origin
        - coat
        - pattern
      properties:
        breed:
          title: Breed
          description: Breed
          type: string
          format: string
        country:
          title: Country
          description: Country
          type: string
          format: string
        origin:
          title: Origin
          description: Origin
          type: string
          format: string
        coat:
          title: Coat
          description: Coat
          type: string
          format: string
        pattern:
          title: Pattern
          description: Pattern
          type: string
          format: string
      type: object
    Link:
      type: object
      required:
        - url
        - label
        - active
      properties:
        url:
          type: string
          example: https://catfact.ninja/breeds?page=2
          nullable: true
        label:
          type: string
        active:
          type: boolean
          example: true
    PageResult:
      type: object
      required:
        - current_page
        - next_page_url
        - path
        - per_page
        - prev_page_url
        - to
        - total
        - first_page_url
        - from
        - last_page
        - last_page_url
        - links
      properties:
        current_page:
          type: integer
          example: 1
        next_page_url:
          type: string
          example: https://catfact.ninja/breeds?page=3
          nullable: true
        path:
          type: string
          example: https://catfact.ninja/breeds
        per_page:
          type: integer
          example: 25
        prev_page_url:
          type: string
          example: https://catfact.ninja/breeds?page=1
          nullable: true
        to:
          type: integer
          example: 25
        total:
          type: integer
          example: 98
        first_page_url:
          type: string
          example: https://catfact.ninja/breeds?page=1
        from:
          type: integer
          example: 1
        last_page:
          type: integer
          example: 4
        last_page_url:
          type: string
          example: https://catfact.ninja/breeds?page=4
        links:
          type: array
          items:
            $ref: '#/components/schemas/Link'
    CatFact:
      title: CatFact model
      description: CatFact
      required:
        - fact
        - length
      properties:
        fact:
          title: Fact
          description: Fact
          type: string
          format: string
        length:
          title: Length
          description: Length
          type: integer
          format: int32
      type: object
tags:
  - name: Facts
    description: Cat Facts
  - name: Breeds
    description: Breeds
security: []
